FROM python:3.7

# Installing dockerize tool
ENV DOCKERIZE_VERSION v0.6.1

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

COPY projects/PDbot/PDbotPython/requirements.txt /app/requirements.txt
RUN python3.7 -m pip install --no-cache-dir -q -r /app/requirements.txt

COPY projects/PDbot/PDbotPython/ /app

WORKDIR /app
EXPOSE 3978
CMD dockerize python3.7 -u app.py